#!/bin/bash

CHROOTDIRS="/root/devel/chroots"
BASE="/var/cache/pbuilder/"
MOUNTS="dev sys proc tmp"


function main {

	if [ "$1" == "" ]; then
		usage
		exit 0
	fi
	TARGET=${CHROOTDIRS}/$1

	echo "* binding /dev, /sys, /tmp and /proc"
	for mp in ${MOUNTS}; do
		mount -o bind /${mp} ${TARGET}/${mp} 2>&1 > /dev/null
	done
	echo "* Chrooting into $TARGET"
	echo
	sleep 1
	chroot $TARGET
	echo "* unbinding /dev, /sys, /tmp and /proc"
	for mp in ${MOUNTS}; do
		umount ${TARGET}/${mp} 2>&1 > /dev/null
	done
	echo "Done"
}

function usage() { 
	echo 
	echo "Chroot into an environement, but also mount /dev, /proc, etc"
        echo 	
	echo "Usage: $0 <chroot directory>"
	echo
}

main $1

