#!/bin/bash




function usage() {
        echo "Usage  : $0 <dist> <arch> [title] [rsync-directory to /usr/src]"
        echo "Example: $0 squeeze i386 banaan"
}


if [ "$#" -lt 2 ]; then
	usage
	exit 1
fi

CHR=`which chr`
if [ -z "$CHR" ]; then
	if [ -x ./chr ]; then
		CHR="./chr"
	else
		echo "cannot find 'chr' executable."
		exit 1
	fi
fi

CHROOTDIRS="/root/devel/chroots"
BASE="/var/cache/pbuilder/"
DIST=$1
ARCH=$2
COWDIR="$BASE/base-$1-$2.cow"
RSYNCDIR=$4
MOUNTS="dev sys proc tmp"

if [ ! -d $COWDIR ]; then
        echo "$COWDIR does not exist, did you specify the correct dist and arch?"
        exit 1;
fi

#Set title if given else create random number
R=$RANDOM
if [ "$3" != "" ]; then
	R=$3
fi

DEST=$CHROOTDIRS/$DIST-$ARCH-$R

if [ ! -d $CHROOTDIRS ]; then
        echo "! chroot directory is set to $CHROOTDIRS, but is not there :("
        exit 1
fi

if [ -d $DEST ]; then
	echo "! chroot directory $DEST is already there"
	exit 1
fi


echo
echo "* copying chroot in $DEST"
cp -r $COWDIR $DEST


if [ "$RSYNCDIR" != "" ]; then
	if [ -d $RSYNCDIR ]; then
		echo "* rsyncing $RSYNCDIR in $DEST/usr/src"
		rsync -a $RSYNCDIR $DEST/usr/src
	else
		echo "* cannot find $RSYNCDIR. No rsync is performed"
	fi
fi


echo "* chrooting into environment"
sleep 1
echo 
$CHR $DEST
echo


echo "- cleanup environment (y/N)?"
read i
if [ "$i" == "y" ] ; then
	
	# doublecheck. All mounts should have been removed when chr exits
	# refuse to cleanup if any still exists
	GOODTOGO="y"
	for mp in ${MOUNTS}; do 
		mount | grep " on $DEST/${mp} " &>/dev/null
		if [ $? -eq 0 ]; then
			GOODTOGO="n"
			echo "$DEST/${mp} still mounted!"
		fi
	done

	if [ "$GOODTOGO" == "y" ]; then
        	echo "* removing $DEST"
        	rm -rf $DEST
	else
		echo "Found mounts into $DEST. Refusing to remove."
	fi

fi

echo "* done"


